# Generated by Django 6.0.6 on 2026-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
