# Generated by Django 6.0.6 on 2026-06-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
